"""add albums

Revision ID: 2ac19077a11d
Revises: ea656ca2045b
Create Date: 2026-01-14 20:11:47.126231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ac19077a11d'
down_revision: Union[str, None] = 'ea656ca2045b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('albums',
    sa.Column('album_guid', sa.Uuid(), nullable=False),
    sa.Column('album_name', sa.Text(), nullable=False),
    sa.Column('album_image', sa.Text(), nullable=True),
    sa.Column('artist_name', sa.Text(), nullable=False),
    sa.Column('last_fm_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('album_guid')
    )
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('album_guid', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key('fk_tracks_album_guid', 'albums', ['album_guid'], ['album_guid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tracks_album_guid', type_='foreignkey')
        batch_op.drop_column('album_guid')
    op.drop_table('albums')
    # ### end Alembic commands ###
