"""require artist and album on track

Revision ID: 42e92d3580a7
Revises: 2ac19077a11d
Create Date: 2026-01-14 20:14:27.480508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42e92d3580a7'
down_revision: Union[str, None] = '2ac19077a11d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.alter_column('album_guid',
                   existing_type=sa.CHAR(length=32),
                   nullable=False)
        batch_op.alter_column('artist_name',
                   existing_type=sa.TEXT(),
                   nullable=False)
        batch_op.alter_column('album_name',
                   existing_type=sa.TEXT(),
                   nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.alter_column('album_name',
                   existing_type=sa.TEXT(),
                   nullable=True)
        batch_op.alter_column('artist_name',
                   existing_type=sa.TEXT(),
                   nullable=True)
        batch_op.alter_column('album_guid',
                   existing_type=sa.CHAR(length=32),
                   nullable=True)
    # ### end Alembic commands ###
