"""saved_to_library

Revision ID: 6ffde3a1a95f
Revises: cdceee4ca012
Create Date: 2025-11-22 15:50:33.863052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ffde3a1a95f'
down_revision: Union[str, None] = 'cdceee4ca012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('saved_to_library', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'saved_to_library')
    # ### end Alembic commands ###
