"""initial

Revision ID: ca179e1bf166
Revises: 
Create Date: 2025-09-19 19:49:56.956066

"""
from typing import Sequence, Union

import sqlalchemy_utc
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca179e1bf166'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracks',
    sa.Column('track_guid', sa.Uuid(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('track_name', sa.Text(), nullable=False),
    sa.Column('artist_name', sa.Text(), nullable=True),
    sa.Column('album_name', sa.Text(), nullable=True),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('released', sa.Text(), nullable=True),
    sa.Column('track_image', sa.Text(), nullable=True),
    sa.Column('artist_image', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('last_fm', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('track_guid')
    )
    op.create_table('history',
    sa.Column('entry_id', sa.Uuid(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('track_guid', sa.Uuid(), nullable=False),
    sa.Column('detected_at', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False),
    sa.Column('started_at', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=True),
    sa.Column('saved_temp_buffer', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['track_guid'], ['tracks.track_guid'], ),
    sa.PrimaryKeyConstraint('entry_id')
    )
    op.create_table('track_ids',
    sa.Column('track_guid', sa.Uuid(), nullable=False),
    sa.Column('track_id', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['track_guid'], ['tracks.track_guid'], ),
    sa.PrimaryKeyConstraint('track_guid', 'track_id')
    )
    op.create_table('saved_music',
    sa.Column('guid', sa.Uuid(), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('history_entry', sa.Uuid(), nullable=True),
    sa.Column('track_guid', sa.Uuid(), nullable=True),
    sa.Column('track', sa.JSON(), nullable=False),
    sa.Column('saved_at', sqlalchemy_utc.sqltypes.UtcDateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Text(), server_default='', nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['history_entry'], ['history.entry_id'], ),
    sa.ForeignKeyConstraint(['track_guid'], ['tracks.track_guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_music')
    op.drop_table('track_ids')
    op.drop_table('history')
    op.drop_table('tracks')
    # ### end Alembic commands ###
