"""library path

Revision ID: cdceee4ca012
Revises: ca179e1bf166
Create Date: 2025-09-20 13:20:55.827155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'cdceee4ca012'
down_revision: Union[str, None] = 'ca179e1bf166'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_music')
    op.add_column('tracks', sa.Column('track_no', sa.BigInteger(), nullable=True))
    op.add_column('tracks', sa.Column('file_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'file_path')
    op.drop_column('tracks', 'track_no')
    op.create_table('saved_music',
    sa.Column('guid', sa.CHAR(length=32), server_default=sa.text('(gen_random_uuid())'), nullable=False),
    sa.Column('history_entry', sa.CHAR(length=32), nullable=True),
    sa.Column('track_guid', sa.CHAR(length=32), nullable=True),
    sa.Column('track', sqlite.JSON(), nullable=False),
    sa.Column('saved_at', sa.DATETIME(), nullable=False),
    sa.Column('source', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('path', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['history_entry'], ['history.entry_id'], ),
    sa.ForeignKeyConstraint(['track_guid'], ['tracks.track_guid'], ),
    sa.PrimaryKeyConstraint('guid')
    )
    # ### end Alembic commands ###
