"""manual history

Revision ID: ea656ca2045b
Revises: 6ffde3a1a95f
Create Date: 2025-11-29 15:43:13.843618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea656ca2045b'
down_revision: Union[str, None] = '6ffde3a1a95f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('is_manual', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'is_manual')
    # ### end Alembic commands ###
